### PR TITLE
landing page

### PR DESCRIPTION
**Pull request by ahmadaccino**
This how it looks. its a little messed up because of the new nav changes tho

Screenshot 2024-04-20 at 9 01 59 PM

### CODE REVIEW

**Comment by ahmadaccino** [comment]
8nhu0y

**Comment by premiare** [comment]
LGTM
Happy Big Bang

**Comment by drjamesj** [comment]
James coffee approves this message.

**Comment by ahmadaccino** [comment]
> James coffee approves this message.

image

**Pull request merged**
